# Generated by Django 4.1.5 on 2023-01-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='owner',
            new_name='user',
        ),
    ]
