# Generated by Django 4.1.5 on 2023-01-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_rename_owner_electronic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='electronic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='electronics.electronic'),
        ),
    ]
