# Generated by Django 4.1.5 on 2023-01-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electronics', '0004_remove_electronic_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='electronics.category'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecommendImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('electronic_recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_images', to='electronics.electronic')),
            ],
        ),
    ]
