# Generated by Django 4.1.5 on 2023-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_electronic_is_parsed_alter_electronic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
