# Generated by Django 4.1.5 on 2023-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0008_parsedelectronic_remove_electronic_is_parsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendimages',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
